services:
  - type: web
    name: campaign-manager-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://jd25user:tBwwU7yUcJoJImTZ@cluster0.3lg9t.mongodb.net/jdcampaignmanager
      - key: JWT_SECRET
        value: mein_geheimer_schluessel_123
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://campaign-manager-frontend-8c0m.onrender.com

  - type: static
    name: campaign-manager-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://campaign-manager-backend-6lv7.onrender.com
